global:
  email-reply-to: nithappu@salesforce.com
  production-branches:
    - main
    - chore/npm-publish
stages:
  build:
    - npm-setup:
        yarn-modern: true
        node-image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_nodejs/sfdc_rhel9_nodejs22_build
    - step:
        name: yarn-build
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_nodejs/sfdc_rhel9_nodejs22_build
        commands:
          - export CLI_BUILD_MODE=release
          - export TARGET_PERSONA=internal
          - yarn --version
          - yarn install
          - yarn build
          - yarn workspace @salesforce-ux/slds-linter lint
          - yarn coverage
  publish:
    - npm-publish:
        working-dir: packages/eslint-plugin-slds
        node-image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_nodejs/sfdc_rhel9_nodejs22_build
    - npm-publish:
        working-dir: packages/eslint-plugin-react-slds
        node-image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_nodejs/sfdc_rhel9_nodejs22_build
    - npm-publish:
        working-dir: packages/cli
        node-image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_nodejs/sfdc_rhel9_nodejs22_build
