compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  salesforce-ux:
    npmRegistryServer: "https://nexus-proxy.repo.local.sfdc.net/nexus/content/groups/npm-all/"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
