# Define the initial scope of analysis for source code (non-test code)
sonar.sources=packages

# Define the initial scope for test files
sonar.tests=packages

# Define which source files should be included in the analysis
sonar.inclusions=packages/**/src/**

# Within the directories defined by sonar.tests, 
# subset of files that will be considered as tests
sonar.test.inclusions=**/tests/**/*.test.spec.ts,**/tests/**/*.test.ts,**/tests/**/*.spec.ts

# Specify the location of LCOV coverage report file
sonar.javascript.lcov.reportPaths=packages/cli/coverage/lcov.info,packages/eslint-plugin-slds/coverage/lcov.info

# Define which files or directories that should be excluded from code coverage metrics
sonar.coverage.exclusions= \
**/dist/**,\
**/build/**,\
**/node_modules/**,\