root: true
env:
  es2021: true
  node: true
parser: "@html-eslint/parser" # ✅ Ensure we are using the correct parser
parserOptions:
  ecmaVersion: 2021
  sourceType: module
ignorePatterns:
  - "node_modules/"
overrides:
  - files:
      - "*.html"
      - "*.cmp"
    parser: "@html-eslint/parser" # ✅ Enforce HTML parser only for these files
    plugins:
      - "@html-eslint"
      - "@salesforce-ux/slds"
    rules:
      "@salesforce-ux/slds/no-bem-class": "error"
      "@salesforce-ux/slds/no-deprecated-slds-classes": "error"
      "@salesforce-ux/slds/modal-close-button-issue": "error"