root: true
env:
  es2021: true
  node: true
parser: "@html-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: "module"
ignorePatterns:
  - "node_modules/"
plugins:
  - "@salesforce-ux/slds"
overrides:
  - files:
      - "**/*.html"
      - "**/*.cmp"
    rules:
      "@salesforce-ux/slds/enforce-bem-usage": "error"
      "@salesforce-ux/slds/no-deprecated-classes-slds2": "error"
      "@salesforce-ux/slds/modal-close-button-issue": "error"
