plugins:
  - "@salesforce-ux/stylelint-plugin-slds"

overrides:
  - files:
      - "**/*.css"
      - "**/*.scss"
    customSyntax: "postcss"
    rules:
      slds/no-slds-class-overrides:
        - severity: warning
      slds/no-important-tag:
        - severity: warning
      # slds/no-hardcoded-values:
      #   - severity: error
      slds/no-hardcoded-values-slds2:
        - severity: warning
      slds/enforce-utility-classes:
        - severity: warning
      slds/no-invalid-tokens-classes:
        - severity: error
      slds/lwc-to-slds-token:
        - severity: warning
      slds/enforce-bem-usage:
        - severity: warning
      slds/no-deprecated-slds-classes:
        - severity: warning
      slds/no-deprecated-slds-hooks:
        - severity: warning
      slds/no-lwc-custom-properties:
        - severity: warning
      slds/no-sds-custom-properties:
        - severity: warning
      slds/no-slds-private-var:
        - severity: warning
      # slds/do-not-use-calc-function:
      #  - severity: warning
      slds/enforce-sds-to-slds-hooks:
        - severity: warning
      slds/reduce-annotations:
        - severity: warning
        
    sourceMap: 
      - false

  - files:
      - "**/*.html"
    customSyntax: "postcss-html"
    rules: {}